# Etapa 1: build del frontend
FROM node:20-alpine AS build
WORKDIR /app

# Copiar package.json desde la carpeta real
COPY userlibrary-frontend/package*.json ./

RUN npm install

# Copiar el código fuente del frontend
COPY userlibrary-frontend/ . 

RUN npm run build

# Etapa 2: servir con Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY userlibrary-frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


